spring:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/jdbcdemo
        username: root
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
agentService:
    getUrl: https://gorest.co.in/public/v2/users
management:
    endpoint:
        health:
            group:
                custom:
                    include=diskSpace,ping
                    show-components=always
                    show-details=always
                status:
                    http-mapping.up=207